version: '2'

services:
  upstream:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

  oauth-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    env_file: oauth2-web.env
    command:
      - --cookie-secure=false
      - --upstream="http://upstream:80"
      - --http-address=http://0.0.0.0:4180
      - --provider=oidc
      - --redirect-url=http://localhost:8080/oauth2/callback
      - --scope=openid profile email offline_access
      - --email-domain="*"
      - --set-xauthrequest
      - --skip-jwt-bearer-tokens=true
  backend:
    image: brndnmtthws/nginx-echo-headers:latest
